/*
-- Query: SELECT * FROM viejooeste.cabins
-- Date: 2015-06-25 21:06
*/
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (1,'Cabaña Buitre','<p>\nSon aves grandes, emblemáticas del oeste, se elevan sin esfuerzo generando al volar un hermoso espectáculo para la vista; de aspecto poco atractivo pero\ncon un encanto especial al posarse en lo más alto de las rocas.\n</p>\n<p>\nEsta cabaña es un <strong>pequeño nido de amor</strong> para que dejes volar tu imaginación  y te escapes de ti mismo.\n</p>',2,150000,300000,'buitre',1,'Buitre es un pequeño nido de amor para que dejes volar tu imaginación y te escapes de ti mismo.','Cabaña Buitre, hoteles en doradal, cabaña tem','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (2,'Cabaña Indio','<p>Hombre fuerte y aguerrido que  siempre vé más allá, tiene la suspicacia para enfrentar cualquier situación, imagina lo inimaginable, lo hace realidad y luego busca los brazos de su amada para entregarle su corazón apasionado.</p>\n<p>Esta cabaña es simplemente un <strong>idilio de amor</strong>.</p>',2,130000,250000,'indio',2,'Hombre fuerte y aguerrido que siempre vé más allá, tiene la suspicacia para enfrentar cualquier situación.','Cabaña Indio, hoteles en doradal, cabaña temá','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (3,'Cabaña Ferrocarril','<p>Va de un lado al otro, llevando y trayendo al sheriff y al forajido, con la única intención de acortar distancias, con la ilusión de llenar de alegría a los que llegan y la misión de dejar enredada en los paisajes desérticos del viejo oeste la tristeza de los que parten de su hogar.</p>\n<p>Esta cabaña te invita a sentir la alegría de los que llegan por fin a un mundo mágico para descansar y divertirse en compañía de familiares y amigos.</p>',6,360000,500000,'ferrocarril',4,'Esta cabaña nos llama a socializar a vivir intensamente cada espacio, cada recuerdo, cada persona.','Cabaña Ferrocarril, hoteles en doradal, cabañ','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (4,'Cabaña Barril','<p>De el los vaqueros y pistoleros de la época extraen el líquido que alivia todas sus penas y en él depositan sus desventuras;  cada trago los libera de sí mismos.</p>\n<p>Esta cabaña nos <strong>embriaga de paz interior</strong> para hacernos descansar en medio de la sencillez.</p>',4,260000,400000,'barril',5,'Esta cabaña nos embriaga de paz interior para hacernos descansar en medio de la sencillez.','Cabaña Barril, hoteles en doradal, cabaña tem','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (5,'Cabaña Pistolero','<p>Protagonistas del desarrollo histórico, estos pistoleros famosos forajidos del lejano oeste, son el único género capaz de escribir la historia en vez de recrearla.</p>\n<p>El pistolero es un hombre habilidoso, cansado, harto de todo, que va de pueblo en pueblo huyendo, en busca de todo y de nada.</p>\n<p>Esta cabaña esta <strong>provista para equilibrar su mente</strong> y brindarle descanso a su cuerpo.</p>',4,240000,350000,'pistolero',6,'El pistolero es un hombre habilidoso, cansado, harto de todo, que va de pueblo en pueblo huyendo, en busca de todo ','Cabaña Pistolero, hoteles en doradal, cabaña ','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (6,'Cabaña Mineros','<p>Hombres decididos que pasaron toda su vida en busca de un futuro mejor, con la firme esperanza de llegar a sus hogares y disfrutar de la recompensa por años de esfuerzo.</p>\n<p>Esta cabaña es la <strong>suite del Viejo Oeste</strong>, está diseñada para deleitarse en el confort y la tranquilidad.</p>',6,360000,500000,'mineros',7,'Esta cabaña es la suite del Viejo Oeste, está diseñada para deleitarse en el confort y la tranquilidad.','Cabaña Mineros, hoteles en doradal, cabaña ','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (7,'Cabaña Caballos','<p>Criaturas de espíritu indomable cuyo galopeo resuena en el viejo oeste, las aventuras de sus jinetes, son también sus aventuras, por eso se convierten en los cómplices perfectos.</p>\n<p>Esta cabaña nos transporta al lugar <strong>ideal para  compartir con amigos y familiares</strong> esas hazañas que le dan sentido a la vida. </p>',6,360000,600000,'caballos',8,'Esta cabaña nos transporta al lugar ideal para compartir con amigos y familiares esas hazañas que le dan sentido a la vida.','Cabaña Caballos, hoteles en doradal, cabaña ','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (8,'Cabaña Cacique','<p>La valentía y la sabiduría con la que dirige su pueblo apache, lo convierte en un ser especial, capaz de hacer familia con su voz y paz con su flecha.</p>\n<p>Esta cabaña está llena de regocijo, hace que evoquemos nuestras raíces.</p>',10,600000,750000,'cacique',11,'Esta cabaña está llena de regocijo, hace que evoquemos nuestras raíces.','Cabaña Cacique, hoteles en doradal, cabaña ','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (9,'Cabaña Establo','<p>Testigo de los hondos suspiros que el exhausto vaquero deja salir desde lo profundo de su ser, esos suspiros que hacen eco en el desértico oeste y que sólo su caballo sabe comprender.</p>\n<p>Esta cabaña, nos invita a establecer <strong>vínculos profundos</strong> con nosotros mismos y con nuestros seres queridos</p>',7,420000,550000,'establo',9,'Esta cabaña, nos invita a establecer vínculos profundos con nosotros mismos y con nuestros seres queridos','Cabaña Establo, hoteles en doradal, cabaña ','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (10,'Cabaña Antiguedades','<p>Todos esos elementos que traen  a la mente los recuerdos de un ayer más familiar, de un ayer donde la unión era el pilar de la sociedad, se reúnen en esta cabaña para ofrecernos descansar en medio de la satisfacción de continuar con la tradición de mostrarle a los más pequeños de dónde venimos.</p>',8,480000,550000,'antiguedades',10,'Esta cabaña es un paraje en nuestro pequeño desierto del oeste donde encontramos agua en movimiento','Cabaña Antiguiedades, hoteles en doradal, cab','2015-07-14 00:58:27','0000-00-00 00:00:00');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (11,'Cabaña Vaqueros','<p>Sinónimo de incansable, explorador enamorado de su pistola y su caballo, capaz de dar todo por nada, es un luchador con un corazón grande, que hizo de la historia un presente y del presente una pasión por la historia de aquella época.</p>\n<p>En la cabaña vaqueros están <strong>esas pequeñas cosas que generan pasión</strong>, sólo eso pasión.</p>',12,720000,850000,'vaqueros',12,'En la cabaña vaqueros están esas pequeñas cosas que generan pasión, sólo eso pasión.','Cabaña Vaqueros, hoteles en doradal, cab','2015-07-14 00:49:42','0000-00-00 00:00:00');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (12,'Cabaña Leñador','<p>Vive en un mundo paralelo, pero no menos interesante, tiene un pacto con la naturaleza y su fiel amiga: el hacha juntos,  golpe a golpe construyen lo impensable para enseñarnos que la naturaleza nos da más de lo que necesitamos.</p>\n<p>Esta cabaña te hará despertar la creatividad y el sentido de pertenencia por el medio ambiente, mientras disfrutas de tu pareja en un ambiente natural.</p>',2,130000,250000,'lenador',2,'Esta cabaña te hará despertar la creatividad y el sentido de pertenencia por el medio ambiente, mientras disfrutas de tu pareja en un ambiente natural.\r','Cabaña Leñador, hoteles en doradal, cab','2015-07-14 00:58:27','0000-00-00 00:00:00');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (13,'Cabaña Comanches',null,2,100000,200000,'comanches',2,null,0,NOW(),NOW());
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (14,'Cabaña Apaches',null,2,100000,200000,'apaches',2,null,0,NOW(),NOW());
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (15,'Cabaña Piel Roja',null,3,150000,250000,'pielroja',3,null,0,NOW(),NOW());
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`order`,`seo_description`,`seo_keywords`,`created_at`,`updated_at`) VALUES (16,'Cabaña Navajos',null,3,150000,250000,'navajas',3,null,0,NOW(),NOW());

