/*
-- Query: SELECT * FROM viejooeste.cabins
-- Date: 2015-06-23 21:41
*/
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (1,'Cabaña Buitre',' Son aves grandes, emblemáticas del oeste, se elevan sin esfuerzo generando al volar un hermoso espectáculo para la vista; de aspecto poco atractivo pero con un encanto especial al posarse en lo más alto de las rocas.\n\nEsta cabaña es un pequeño nido de amor para que dejes volar tu imaginación y te escapes de ti mismo.',2,150000,300000,'buitre','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (2,'Cabaña Indio',' Hombre fuerte y aguerrido que siempre vé más allá, tiene la suspicacia para enfrentar cualquier situación, imagina lo inimaginable, lo hace realidad y luego busca los brazos de su amada para entregarle su corazón apasionado.\n\nEsta cabaña es simplemente un idilio de amor.',2,150000,250000,'indio','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (3,'Cabaña Ferrocarril',' Dicen que las armas están hechas para igualar a los hombres, en ese viejo oeste así lo creían y por ello adoptaron el rifle como una parte más de su cuerpo, con él se defienden, con él enamoran, con él se divierten, con él viven.  Esta cabaña n...',4,240000,400000,'ferrocarril','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (4,'Cabaña Establo',' Testigo de los hondos suspiros que el exhausto vaquero deja salir desde lo profundo de su ser, esos suspiros que hacen eco en el desértico oeste y que sólo su caballo sabe comprender.\n\nEsta cabaña, nos invita a establecer vínculos profundos con nosotros mismos y con nuestros seres queridos ',4,240000,400000,'establo','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (5,'Cabaña Pistolero',' Protagonistas del desarrollo histórico, estos pistoleros famosos forajidos del lejano oeste, son el único género capaz de escribir la historia en vez de recrearla.\n\nEl pistolero es un hombre habilidoso, cansado, harto de todo, que va de pueblo en pueblo huyendo, en busca de todo y de nada. Esta cabaña esta provista para equilibrar su mente y brindarle descanso a su cuerpo. ',4,240000,400000,'pistolero','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (6,'Cabaña Mineros',' Hombres decididos que pasaron toda su vida en busca de un futuro mejor, con la firme esperanza de llegar a sus hogares y disfrutar de la recompensa por años de esfuerzo.\n\nEsta cabaña es la suite del Viejo Oeste, está diseñada para deleitarse en el confort y la tranquilidad. ',6,360000,500000,'mineros','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (7,'Cabaña Caballos',' Criaturas de espíritu indomable cuyo galopeo resuena en el viejo oeste, las aventuras de sus jinetes, son también sus aventuras, por eso se convierten en los cómplices perfectos.\n\nEsta cabaña nos transporta al lugar ideal para compartir con amigos y familiares esas hazañas que le dan sentido a la vida. ',6,360000,600000,'caballos','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (8,'Cabaña Cacique',' La valentía y la sabiduría con la que dirige su pueblo apache, lo convierte en un ser especial, capaz de hacer familia con su voz y paz con su flecha.\n\nEsta cabaña está llena de regocijo, hace que evoquemos nuestras raíces. ',10,600000,900000,'cacique','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (9,'Cacique Barril',' De el los vaqueros y pistoleros de la época extraen el líquido que alivia todas sus penas y en él depositan sus desventuras; cada trago los libera de sí mismos.\n\nEsta cabaña nos embriaga de paz interior para hacernos descansar en medio de la sencillez. ',7,420000,500000,'barril','2015-06-21 17:06:10','2015-06-21 17:06:10');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (10,'Cabaña Antiguedades',' Inspirada en el barril de ron y wiski de la época de la conquista del viejo oeste, donde toman un baño los vaqueros luego de un largo viaje.\n\nEsta cabaña es un paraje en nuestro pequeño desierto del oeste donde encontramos agua en movimiento rodeada de vegetación, ideal para compartir en familia. ',8,480000,550000,'antiguedades','0000-00-00 00:00:00','0000-00-00 00:00:00');
INSERT INTO `cabins` (`idcabin`,`name`,`description`,`capacity`,`rate_ls`,`rate_hs`,`slug`,`created_at`,`updated_at`) VALUES (11,'Cabaña Vaqueros',' Sinónimo de incansable, explorador enamorado de su pistola y su caballo, capaz de dar todo por nada, es un luchador con un corazón grande, que hizo de la historia un presente y del presente una pasión por la historia de aquella época.  En la cabaña...',12,720000,1000000,'vaqueros','0000-00-00 00:00:00','0000-00-00 00:00:00');
